// src/ui-react/hooks/useContentOperations.js
import { useState, useCallback } from 'react';
import { createContent } from '../api/client.js';

/**
 * Hook for content/cue creation operations
 */
export function useContentOperations({ expandNode, onContentCreated }) {
  const [contentPrompt, setContentPrompt] = useState('');
  const [contentCueId, setContentCueId] = useState('');
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState(null);

  const createContentItem = useCallback(async (actorId, contentType, sectionId) => {
    try {
      setCreating(true);
      setError(null);
      
      const result = await createContent({
        actor_id: actorId,
        content_type: contentType,
        section_id: sectionId,
        cue_id: contentCueId,
        prompt: contentPrompt || undefined,
      });

      if (result && result.content && onContentCreated) {
        if (Array.isArray(result.content)) {
          result.content.forEach(item => onContentCreated(item));
        } else {
          onContentCreated(result.content);
        }
        
        // Auto-expand to show the new content
        if (expandNode) {
          expandNode('actors');
          expandNode(`actor-${actorId}`);
          if (sectionId) {
            expandNode(`section-${sectionId}`);
          }
        }
        
        if (result.message) {
          setError(result.message);
        }
      }
      
      setContentPrompt('');
      setContentCueId('');
    } catch (err) {
      setError(err.message || String(err));
    } finally {
      setCreating(false);
    }
  }, [contentPrompt, contentCueId, expandNode, onContentCreated]);

  return {
    contentPrompt,
    contentCueId,
    creating,
    error,
    setContentPrompt,
    setContentCueId,
    setError,
    createContent: createContentItem,
  };
}

// src/ui-solid/hooks/useContentOperations.jsx
import { createSignal } from 'solid-js';
import { createContent } from '../api/client.js';

/**
 * Hook for content/cue creation operations
 */
export function useContentOperations(props) {
    const [contentPrompt, setContentPrompt] = createSignal('');
    const [contentName, setContentName] = createSignal('');
    const [creating, setCreating] = createSignal(false);
    const [error, setError] = createSignal(null);

    const createContentItem = async (ownerId, ownerType, contentType, sectionId) => {
        try {
            setCreating(true);
            setError(null);

            const result = await createContent({
                owner_id: ownerId,
                owner_type: ownerType,
                content_type: contentType,
                section_id: sectionId,
                names: contentName(),
                prompt: contentPrompt() || undefined,
            });

            if (result && result.content && props.onContentCreated) {
                if (Array.isArray(result.content)) {
                    result.content.forEach(item => props.onContentCreated(item));
                } else {
                    props.onContentCreated(result.content);
                }

                // Auto-expand to show the new content
                if (props.expandNode) {
                    props.expandNode(ownerType === 'actor' ? 'actors' : 'scenes');
                    props.expandNode(`${ownerType}-${ownerId}`);
                    if (sectionId) {
                        props.expandNode(`section-${sectionId}`);
                    }
                }

                if (result.message) {
                    setError(result.message);
                }
            }

            setContentPrompt('');
            setContentName('');
        } catch (err) {
            setError(err.message || String(err));
        } finally {
            setCreating(false);
        }
    };

    return {
        contentPrompt,
        contentName,
        creating,
        error,
        setContentPrompt,
        setContentName,
        setError,
        createContent: createContentItem,
    };
}
