// src/ui/components/SectionManagement.jsx
import React from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';
import { DESIGN_SYSTEM } from '../theme/designSystem.js';

export default function SectionManagement({ 
  actor, 
  sections, 
  onCreateSection, 
  creatingContent 
}) {
  return (
    <Box sx={{ mt: DESIGN_SYSTEM.spacing.sectionGap }}>
      <Typography variant="subtitle2" gutterBottom sx={DESIGN_SYSTEM.typography.sectionTitle}>
        Content Sections
      </Typography>
      <Typography variant="body2" color="text.secondary" gutterBottom sx={DESIGN_SYSTEM.typography.body}>
        Create multiple sections for different types of content (e.g., combat dialog, story music, etc.)
      </Typography>
      
      <Stack spacing={DESIGN_SYSTEM.spacing.elementGap} sx={{ mt: DESIGN_SYSTEM.spacing.elementGap }}>
        {/* Show existing sections categorized by type */}
        {['dialogue', 'music', 'sfx'].map((contentType) => {
          const sectionsOfType = sections.filter(
            (s) => s.actor_id === actor.id && s.content_type === contentType
          );
          if (sectionsOfType.length === 0) return null;
          
          return (
            <Box key={contentType}>
              <Typography
                variant="body2"
                sx={{
                  ...DESIGN_SYSTEM.typography.body,
                  fontWeight: 500,
                  mb: DESIGN_SYSTEM.spacing.tightGap,
                }}
              >
                {contentType} sections:
              </Typography>
              {sectionsOfType.map((section) => (
                <Box
                  key={section.id}
                  sx={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: DESIGN_SYSTEM.spacing.elementGap,
                    ml: DESIGN_SYSTEM.spacing.elementGap,
                  }}
                >
                  <Typography
                    variant="body2"
                    sx={{ minWidth: 120, ...DESIGN_SYSTEM.typography.body }}
                  >
                    {section.name || section.content_type}
                  </Typography>
                  <Typography
                    variant="body2"
                    color="success.main"
                    sx={DESIGN_SYSTEM.typography.body}
                  >
                    ✓ section exists
                  </Typography>
                </Box>
              ))}
            </Box>
          );
        })}
        
        {/* Add new section buttons */}
        <Box
          sx={{
            display: 'flex',
            gap: DESIGN_SYSTEM.spacing.componentGap,
            flexWrap: 'wrap',
            mt: DESIGN_SYSTEM.spacing.elementGap,
          }}
        >
          <Button
            size="small"
            variant="outlined"
            onClick={() => onCreateSection(actor.id, 'dialogue')}
            disabled={creatingContent}
            sx={DESIGN_SYSTEM.typography.small}
          >
            + Add dialogue section
          </Button>
          <Button
            size="small"
            variant="outlined"
            onClick={() => onCreateSection(actor.id, 'music')}
            disabled={creatingContent}
            sx={DESIGN_SYSTEM.typography.small}
          >
            + Add music section
          </Button>
          <Button
            size="small"
            variant="outlined"
            onClick={() => onCreateSection(actor.id, 'sfx')}
            disabled={creatingContent}
            sx={DESIGN_SYSTEM.typography.small}
          >
            + Add sfx section
          </Button>
        </Box>
      </Stack>
    </Box>
  );
}

// src/ui-solid/components/SectionManagement.jsx
import { Box, Typography, Button, Stack } from '@suid/material';
import { For, Show } from 'solid-js';

export default function SectionManagement(props) {
    // props: owner, ownerType, sections, onCreateSection, creatingContent

    return (
        <Box sx={{ mt: 3 }}>
            <Typography variant="subtitle2" gutterBottom sx={{ textTransform: 'uppercase', fontSize: '0.75rem', letterSpacing: '0.05em' }}>
                Content Sections
            </Typography>
            <Typography variant="body2" color="text.secondary" gutterBottom>
                Create multiple sections for different types of content (e.g., combat dialogue, story music, etc.)
            </Typography>

            <Stack spacing={1} sx={{ mt: 1 }}>
                {/* Show existing sections categorized by type */}
                <For each={['dialogue', 'music', 'sfx', 'image', 'video']}>
                    {(contentType) => {
                        const sectionsOfType = () => props.sections.filter(
                            (s) => s.owner_id === props.owner.id && s.owner_type === props.ownerType && s.content_type === contentType
                        );

                        return (
                            <Show when={sectionsOfType().length > 0}>
                                <Box>
                                    <Typography
                                        variant="body2"
                                        sx={{
                                            fontWeight: 500,
                                            mb: 0.5,
                                        }}
                                    >
                                        {contentType} sections:
                                    </Typography>
                                    <For each={sectionsOfType()}>
                                        {(section) => (
                                            <Box
                                                sx={{
                                                    display: 'flex',
                                                    alignItems: 'center',
                                                    gap: 1,
                                                    ml: 1,
                                                }}
                                            >
                                                <Typography
                                                    variant="body2"
                                                    sx={{ minWidth: 120 }}
                                                >
                                                    {section.name || section.content_type}
                                                </Typography>
                                                <Typography
                                                    variant="body2"
                                                    color="success.main"
                                                >
                                                    ✓ section exists
                                                </Typography>
                                            </Box>
                                        )}
                                    </For>
                                </Box>
                            </Show>
                        );
                    }}
                </For>

                {/* Add new section buttons */}
                <Box
                    sx={{
                        display: 'flex',
                        gap: 1,
                        flexWrap: 'wrap',
                        mt: 1,
                    }}
                >
                    <For each={['dialogue', 'music', 'sfx', 'image', 'video']}>
                        {(type) => (
                            <Button
                                size="small"
                                variant="outlined"
                                onClick={() => props.onCreateSection(props.owner.id, props.ownerType, type)}
                                disabled={props.creatingContent}
                                sx={{ fontSize: '0.75rem' }}
                            >
                                + Add {type} section
                            </Button>
                        )}
                    </For>
                </Box>
            </Stack>
        </Box>
    );
}
